# Generated by Django 5.1 on 2024-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=120)),
                ('exp', models.IntegerField(max_length=2)),
                ('image', models.ImageField(upload_to='media/member')),
            ],
        ),
    ]
