# Generated by Django 5.1 on 2024-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/successStory')),
            ],
        ),
    ]
