# Generated by Django 5.1 on 2024-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0004_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='media/feedback')),
            ],
        ),
    ]
