# Generated by Django 5.1 on 2024-09-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0007_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='carousel_videos/')),
                ('caption_title', models.CharField(max_length=100)),
                ('caption_subtitle', models.CharField(max_length=200)),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='exp',
            field=models.IntegerField(),
        ),
    ]
