# Generated by Django 5.1 on 2024-09-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0009_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
