# Generated by Django 5.1 on 2024-09-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0010_delete_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
