# Generated by Django 5.1 on 2024-10-09 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0012_member_member_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessStory',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
