# Generated by Django 5.1 on 2024-10-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0015_remove_subscriber_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='newsletters',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='forensicApp.newsletter'),
        ),
    ]
