# Generated by Django 5.1 on 2024-10-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0016_subscriber_newsletters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='newsletters',
        ),
    ]
