# Generated by Django 5.1 on 2024-11-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicApp', '0017_remove_subscriber_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
